"use client";
import {useState} from "react";import {EditorDialog} from "./editor-dialog";import {ActionForm} from "./action-form";import {updateOrderDetails} from "@/app/actions";
export function OrderEditor({order:o,customers,suppliers}:{order:any;customers:{id:string;full_name:string}[];suppliers:{id:string;name:string}[]}){
 const [open,setOpen]=useState(false);return <><button type="button" className="secondary-btn compact" onClick={()=>setOpen(true)}>Editar pedido</button>{open&&<EditorDialog title={"Editar "+o.order_number} onClose={()=>setOpen(false)}><ActionForm action={updateOrderDetails} className="popover-form inline-form" submitLabel="Guardar pedido"><input type="hidden" name="order_id" value={o.id}/>
 <div className="form-grid"><label>Número de pedido<input name="order_number" defaultValue={o.order_number} required/></label><label>Cliente<select name="customer_id" defaultValue={o.customer_id??""}><option value="">Sin cliente</option>{customers.map(c=><option key={c.id} value={c.id}>{c.full_name}</option>)}</select></label>
 <label>Proveedor<select name="supplier_id" defaultValue={o.supplier_id??""}><option value="">Sin proveedor</option>{suppliers.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Costo de envío<input name="shipping_cost" type="number" min="0" step="0.01" defaultValue={o.shipping_cost}/></label></div>
 {(o.order_items??[]).map((i:any)=><fieldset key={i.id}><legend>Producto del pedido</legend><input type="hidden" name="item_id" value={i.id}/><div className="form-grid"><label>Descripción<input name="item_name" defaultValue={i.product_name} required/></label><label>Talla / variante<input name="item_size" defaultValue={i.size??""}/></label><label>Cantidad<input name="item_quantity" type="number" min="1" step="1" defaultValue={i.quantity} required/></label><label>Precio por unidad<input name="item_price" type="number" min="0" step="0.01" defaultValue={i.unit_price} required/></label><label>Costo por unidad<input name="item_cost" type="number" min="0" step="0.01" defaultValue={i.unit_cost} required/></label></div></fieldset>)}
 <label>Notas<textarea name="notes" defaultValue={o.notes??""}/></label><p>El total, costo, utilidad y saldo se recalculan. Los pagos ya registrados se conservan.</p></ActionForm></EditorDialog>}</>;
}
