"use client";
import {useState} from "react";import {EditorDialog} from "./editor-dialog";
import {ActionForm} from "./action-form";import {deleteRecord,updateRecord} from "@/app/actions";
export type Field={key:string;label:string;type?:string;required?:boolean;options?:string[]};
export function DeleteRecord({table,id,label,warning}:{table:string;id:string;label:string;warning?:string}){
 const [open,setOpen]=useState(false);return <><button type="button" className="danger-link" onClick={()=>setOpen(true)}>Eliminar</button>{open&&<EditorDialog title="Eliminar registro" onClose={()=>setOpen(false)}><ActionForm action={deleteRecord} className="popover-form inline-form" submitLabel="Eliminar registro"><input type="hidden" name="record_table" value={table}/><input type="hidden" name="record_id" value={id}/><p><b>{label}</b></p><p>{warning??"Se eliminará este registro definitivamente."}</p><label className="confirmation"><input type="checkbox" name="confirm_delete" value="yes" required/> Confirmo la eliminación</label></ActionForm></EditorDialog>}</>;
}
export function RecordControls({table,row,fields,label,warning}:{table:string;row:Record<string,any>;fields:Field[];label:string;warning?:string}){
 const [open,setOpen]=useState(false);return <div className="record-actions"><button type="button" className="secondary-btn compact" onClick={()=>setOpen(true)}>Editar</button>{open&&<EditorDialog title="Editar registro" onClose={()=>setOpen(false)}><ActionForm key={JSON.stringify(row)} action={updateRecord} className="popover-form inline-form" submitLabel="Guardar cambios"><input type="hidden" name="record_table" value={table}/><input type="hidden" name="record_id" value={row.id}/><div className="form-grid">{fields.map(f=><label key={f.key}>{f.label}{f.options?<select name={f.key} defaultValue={row[f.key]??f.options[0]}>{[...new Set([...f.options,...(row[f.key]?[String(row[f.key])]:[])])].map(v=><option key={v}>{v}</option>)}</select>:f.type==="textarea"?<textarea name={f.key} defaultValue={row[f.key]??""} maxLength={1000}/>:<input name={f.key} type={f.type??"text"} defaultValue={f.type==="datetime-local"?row[f.key]?.slice(0,16)??"":row[f.key]??""} required={f.required} min={f.type==="number"?"0":undefined} step={f.type==="number"?"0.01":undefined}/>}</label>)}</div></ActionForm></EditorDialog>}<DeleteRecord table={table} id={row.id} label={label} warning={warning}/></div>;
}
