import {TelegramSetup} from "@/components/telegram-setup";
import {pauseTelegram,retryTelegram} from "@/app/notification-actions";
import {AppShell} from "@/components/app-shell";import {ActionForm} from "@/components/action-form";
import {createPaymentMethod,updatePaymentMethod} from "@/app/actions";import {DeleteRecord} from "@/components/record-controls";import {createClient} from "@/lib/supabase/server";import {BANKS} from "@/lib/payment-methods";
export default async function Page(){const s=await createClient();const {data:{user}}=await s.auth.getUser();const {data:methods,error}=await s.from("payment_methods").select("id,name").order("name");if(error)throw new Error(error.message);
 const [{data:telegram,error:tgError},{data:notifications,error:noticeError}]=await Promise.all([s.rpc("telegram_status"),s.from("dispatch_notifications").select("id,kind,status,created_at,orders(order_number)").order("created_at",{ascending:false}).limit(15)]);if(tgError||noticeError)throw new Error("No se pudo cargar la configuración de avisos");
 const statusNames:Record<string,string>={pending:"Pendiente",sending:"Enviando",sent:"Enviado",failed:"Falló",uncertain:"Envío sin confirmar",skipped:"Omitido: pedido cambió"};const kindNames:Record<string,string>={ready:"Listo para despachar",paid:"Pago completo",reminder:"Recordatorio de envío",test:"Prueba de conexión"};
 return <AppShell><section className="page-head"><div><p className="eyebrow">SISTEMA</p><h1>Configuración</h1><p>Controla tus opciones de cobro y la información de tu negocio.</p></div></section><section className="grid-2">
 <div className="card editor-card"><h3>Administrador</h3><p>Usuario: leandroaldair</p><p>{user?.email}</p><p>Moneda USD · Ecuador</p><a href="/ayuda" className="secondary-btn">Guía de operación</a><h3>Bancos receptores</h3><p>{BANKS.join(" · ")}</p><p>El banco identifica dónde recibiste el dinero; el método indica si fue transferencia, depósito, efectivo u otro.</p></div>
 <div className="card editor-card"><h3>Métodos de pago</h3><p>Editar o eliminar un método cambia la lista para nuevos cobros. Los pagos anteriores conservan el nombre que tenían y pueden corregirse en Pagos.</p>
 <ActionForm action={createPaymentMethod} className="popover-form inline-form" submitLabel="Agregar método"><label>Nombre<input name="name" maxLength={80} required placeholder="Ej. Transferencia, Depósito, DeUna"/></label></ActionForm>
 <div className="method-list">{(methods??[]).map(m=><div key={m.id} className="method-item"><strong>{m.name}</strong><details><summary>Editar nombre</summary><ActionForm key={m.name} action={updatePaymentMethod} className="popover-form inline-form" submitLabel="Renombrar"><input type="hidden" name="method_id" value={m.id}/><label>Nombre<input name="name" defaultValue={m.name} maxLength={80} required/></label></ActionForm></details><DeleteRecord table="payment_methods" id={m.id} label={m.name} warning="Se quitará de nuevos cobros. Los pagos anteriores se conservan."/></div>)}</div>
 </div></section><section className="grid-2" style={{marginTop:24}}><div className="card editor-card"><h3>Avisos internos por Telegram</h3><p>Pago completo, pedido listo para salir y recordatorio diario desde las 09:00 de Ecuador cuando llegue la fecha de envío. Los avisos se procesan cada minuto.</p><p><strong>{telegram?.enabled?"Conectado a "+telegram.chat_title:telegram?.chat_title?"Pausado · "+telegram.chat_title:"Sin conectar"}</strong></p>{telegram?.enabled&&<ActionForm action={pauseTelegram} submitLabel="Pausar avisos"/>}<details open={!telegram?.enabled}><summary>{telegram?.chat_title?"Cambiar o reactivar conexión":"Conectar Telegram"}</summary><TelegramSetup/></details></div>
 <div className="card editor-card"><h3>Últimos avisos</h3><p>Actualiza esta página para consultar el resultado.</p>{!notifications?.length&&<p>Todavía no hay avisos.</p>}{notifications?.map((n:any)=><div key={n.id} className="method-item"><strong>{kindNames[n.kind]??n.kind} · {n.orders?.order_number??"WAVESS"}</strong><p>{statusNames[n.status]??n.status}</p>{["failed","uncertain"].includes(n.status)&&<details><summary>Reintentar aviso</summary><p>{n.status==="uncertain"?"Revisa primero Telegram: podría haberse recibido y reenviarlo lo duplicaría.":"Corrige la conexión si es necesario antes de reenviar."}</p><ActionForm action={retryTelegram} submitLabel="Reenviar"><input type="hidden" name="notification_id" value={n.id}/></ActionForm></details>}</div>)}</div></section></AppShell>;
}
